format_version: v1.0
configName: pic32mk_mcj_curiosity_pro
folderName: pic32mk_mcj_curiosity_pro
frameworkPath: C:\h3
processor: PIC32MK0512MCJ064
projectName: pic32mk_mcj_curiosity_pro
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32MK-MC_DFP\1.11.151\atdf\PIC32MK0512MCJ064.atdf
